// Pac-Study Knowledge Library & Category Definitions

export interface CollectibleItem {
  id: string;
  name: string;
  category: string;
  description: string;
  color: string;
  accentColor: string;
}

export interface PacCategory {
  id: string;
  name: string;
  tagline: string;
  description: string;
  themeColor: string;
  wallColor: string;
  wallGlow: string;
  bgGradient: string;
  accentColor: string;
  items: CollectibleItem[];
}

export const PAC_CATEGORIES: PacCategory[] = [
  {
    id: 'MATHEMATICS',
    name: 'MATHEMATICS',
    tagline: 'NUMBERS, PROOFS & SPATIAL FORMS',
    description: 'Explore geometric structures, mathematical constants, calculus symbols, and dimensional theorems.',
    themeColor: '#3B82F6',
    wallColor: '#1E40AF',
    wallGlow: 'rgba(59, 130, 246, 0.4)',
    bgGradient: 'from-blue-950 via-slate-900 to-indigo-950',
    accentColor: '#93C5FD',
    items: [
      { id: 'math-pi', name: 'Pi Symbol (π)', category: 'MATHEMATICS', description: "Mathematical constant representing the ratio of a circle's circumference to its diameter (~3.14159).", color: '#60A5FA', accentColor: '#BFDBFE' },
      { id: 'math-sqrt', name: 'Square Root Symbol (√)', category: 'MATHEMATICS', description: 'Radical symbol denoting the non-negative value that yields the original number when squared.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'math-infinity', name: 'Infinity Symbol (∞)', category: 'MATHEMATICS', description: 'Lemniscate representing an unbounded quantity larger than any finite real number.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'math-integral', name: 'Integral Symbol (∫)', category: 'MATHEMATICS', description: 'Calculus notation representing continuous summation and the area under a curve.', color: '#A78BFA', accentColor: '#DDD6FE' },
      { id: 'math-summation', name: 'Summation Symbol (∑)', category: 'MATHEMATICS', description: 'Capital Greek sigma denoting the discrete addition of a sequence of terms.', color: '#3B82F6', accentColor: '#93C5FD' },
      { id: 'math-triangle', name: 'Triangle', category: 'MATHEMATICS', description: 'Three-sided polygon whose interior angles always sum to 180 degrees in Euclidean space.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'math-circle', name: 'Circle', category: 'MATHEMATICS', description: 'Set of all points in a plane equidistant from a fixed central point.', color: '#EC4899', accentColor: '#FBCFE8' },
      { id: 'math-cube', name: 'Cube', category: 'MATHEMATICS', description: 'Three-dimensional regular polyhedron with six identical square faces.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'math-sphere', name: 'Sphere', category: 'MATHEMATICS', description: 'Symmetrical three-dimensional geometric object where every surface point is equidistant from the center.', color: '#06B6D4', accentColor: '#A5F3FC' },
      { id: 'math-angle', name: 'Angle', category: 'MATHEMATICS', description: 'Geometric figure formed by two rays sharing a common endpoint called the vertex.', color: '#F97316', accentColor: '#FED7AA' },
      { id: 'math-fraction', name: 'Fraction', category: 'MATHEMATICS', description: 'Numerical representation of a part of a whole, expressed as numerator over denominator.', color: '#14B8A6', accentColor: '#99F6E4' },
      { id: 'math-percent', name: 'Percentage (%)', category: 'MATHEMATICS', description: 'Ratio or fraction expressed as a fraction of 100 using the percent sign.', color: '#8B5CF6', accentColor: '#C4B5FD' },
      { id: 'math-coord', name: 'Coordinate Plane', category: 'MATHEMATICS', description: 'Two-dimensional grid surface defined by perpendicular intersecting axes (x and y).', color: '#6366F1', accentColor: '#C7D2FE' },
      { id: 'math-line-graph', name: 'Line Graph', category: 'MATHEMATICS', description: 'Chart displaying quantitative data as a series of connected points over an interval.', color: '#0EA5E9', accentColor: '#7DD3FC' },
      { id: 'math-dice', name: 'Dice Probability', category: 'MATHEMATICS', description: 'Study of chance outcomes based on combinatorial possibilities of uniform polyhedral dice.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'math-algebra', name: 'Algebra Equation', category: 'MATHEMATICS', description: 'Mathematical statement showing equality between two expressions containing variables.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'math-matrix', name: 'Matrix', category: 'MATHEMATICS', description: 'Rectangular array of numbers or symbols arranged in rows and columns.', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'math-vector', name: 'Vector', category: 'MATHEMATICS', description: 'Quantity possessing both magnitude and direction in coordinate space.', color: '#3B82F6', accentColor: '#93C5FD' },
      { id: 'math-fibonacci', name: 'Fibonacci Spiral', category: 'MATHEMATICS', description: 'Logarithmic spiral created by connecting quarter-circle arcs in Fibonacci-tiled squares.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'math-golden-ratio', name: 'Golden Ratio Spiral (φ)', category: 'MATHEMATICS', description: 'Geometric proportion (phi ≈ 1.618) recurring in art, nature, and geometry.', color: '#D97706', accentColor: '#FDE68A' },
    ],
  },
  {
    id: 'SCIENCE',
    name: 'SCIENCE',
    tagline: 'EMPIRICAL DISCOVERY & LABORATORY INQUIRY',
    description: 'Traverse scientific laboratories filled with atoms, telescopes, microscopes, and celestial bodies.',
    themeColor: '#10B981',
    wallColor: '#065F46',
    wallGlow: 'rgba(16, 185, 129, 0.4)',
    bgGradient: 'from-emerald-950 via-slate-900 to-teal-950',
    accentColor: '#6EE7B7',
    items: [
      { id: 'sci-atom', name: 'Atom', category: 'SCIENCE', description: 'Basic unit of chemical elements consisting of a dense nucleus surrounded by orbiting electrons.', color: '#34D399', accentColor: '#A7F3D0' },
      { id: 'sci-molecule', name: 'Molecule', category: 'SCIENCE', description: 'Electrically neutral group of two or more atoms held together by covalent chemical bonds.', color: '#2DD4BF', accentColor: '#99F6E4' },
      { id: 'sci-dna', name: 'DNA Double Helix', category: 'SCIENCE', description: 'Polymer nucleic acid structure storing biological hereditary instructions in twisted strands.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'sci-microscope', name: 'Microscope', category: 'SCIENCE', description: 'Optical instrument used to view specimens and cells too small for the unaided human eye.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'sci-testtube', name: 'Test Tube', category: 'SCIENCE', description: 'Cylindrical glass container used in laboratories to hold, mix, and heat small chemical samples.', color: '#F472B6', accentColor: '#FBCFE8' },
      { id: 'sci-beaker', name: 'Beaker', category: 'SCIENCE', description: 'Cylindrical laboratory vessel with a flat bottom and pouring spout for mixing liquids.', color: '#60A5FA', accentColor: '#BFDBFE' },
      { id: 'sci-burner', name: 'Bunsen Burner', category: 'SCIENCE', description: 'Laboratory gas burner producing a clean, adjustable flame for heating and sterilizing.', color: '#FB923C', accentColor: '#FED7AA' },
      { id: 'sci-petri', name: 'Petri Dish', category: 'SCIENCE', description: 'Shallow transparent cylindrical dish used by biologists to culture cells and microorganisms.', color: '#A3E635', accentColor: '#D9F99D' },
      { id: 'sci-magnet', name: 'Magnet', category: 'SCIENCE', description: 'Material or object producing a magnetic field that attracts iron and ferromagnetic metals.', color: '#F87171', accentColor: '#FECACA' },
      { id: 'sci-thermometer', name: 'Thermometer', category: 'SCIENCE', description: 'Calibrated diagnostic device used to measure temperature and thermal energy quantitatively.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'sci-telescope', name: 'Telescope', category: 'SCIENCE', description: 'Optical instrument magnifying electromagnetic radiation to observe distant celestial bodies.', color: '#93C5FD', accentColor: '#DBEAFE' },
      { id: 'sci-solarsystem', name: 'Solar System', category: 'SCIENCE', description: 'Gravitationally bound system of the Sun and the celestial bodies orbiting it.', color: '#FBBF24', accentColor: '#FDE68A' },
      { id: 'sci-earth', name: 'Earth', category: 'SCIENCE', description: 'Third planet from the Sun and the only astronomical body known to harbor active life.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'sci-moon', name: 'Moon', category: 'SCIENCE', description: "Earth's only natural satellite, exerting gravitational force driving ocean tides.", color: '#CBD5E1', accentColor: '#F1F5F9' },
      { id: 'sci-meteor', name: 'Meteor', category: 'SCIENCE', description: 'Streak of light produced when a meteoroid vaporizes upon entering Earth atmosphere.', color: '#F97316', accentColor: '#FED7AA' },
      { id: 'sci-fossil', name: 'Fossil', category: 'SCIENCE', description: 'Preserved mineralized remains or traces of ancient organisms from past geological ages.', color: '#A8A29E', accentColor: '#E7E5E4' },
      { id: 'sci-crystal', name: 'Crystal', category: 'SCIENCE', description: 'Solid material whose microscopic constituents are arranged in a highly ordered lattice.', color: '#C084FC', accentColor: '#E9D5FF' },
      { id: 'sci-flask', name: 'Chemical Flask', category: 'SCIENCE', description: 'Conical vessel designed for swirling chemicals without risk of accidental spilling.', color: '#2DD4BF', accentColor: '#99F6E4' },
      { id: 'sci-slide', name: 'Microscope Slide', category: 'SCIENCE', description: 'Thin flat piece of glass used to support specimen slices under optical magnification.', color: '#94A3B8', accentColor: '#E2E8F0' },
      { id: 'sci-goggles', name: 'Laboratory Goggles', category: 'SCIENCE', description: 'Protective eyewear shielding vision against hazardous chemical splashes and debris.', color: '#38BDF8', accentColor: '#BAE6FD' },
    ],
  },
  {
    id: 'BIOLOGY',
    name: 'BIOLOGY',
    tagline: 'LIVING SYSTEMS, BOTANY & ANATOMICAL CELLS',
    description: 'Explore natural flora, African savanna fauna, cellular organelles, and genetic building blocks.',
    themeColor: '#22C55E',
    wallColor: '#15803D',
    wallGlow: 'rgba(34, 197, 94, 0.4)',
    bgGradient: 'from-green-950 via-slate-900 to-emerald-950',
    accentColor: '#86EFAC',
    items: [
      { id: 'bio-oak', name: 'Oak Tree', category: 'BIOLOGY', description: 'Deciduous hardwood tree that produces acorns and supports diverse woodland ecosystems.', color: '#4ADE80', accentColor: '#BBF7D0' },
      { id: 'bio-pine', name: 'Pine Tree', category: 'BIOLOGY', description: 'Coniferous evergreen tree characterized by needle foliage and woody seed cones.', color: '#16A34A', accentColor: '#86EFAC' },
      { id: 'bio-palm', name: 'Palm Tree', category: 'BIOLOGY', description: 'Flowering evergreen perennial adapted to tropical climates with large fan-like fronds.', color: '#22C55E', accentColor: '#A7F3D0' },
      { id: 'bio-baobab', name: 'Baobab Tree', category: 'BIOLOGY', description: 'Iconic African tree known for its enormous water-storing trunk and remarkable longevity.', color: '#B45309', accentColor: '#FDE68A' },
      { id: 'bio-maple', name: 'Maple Tree', category: 'BIOLOGY', description: 'Deciduous forest tree famous for its distinct palmate foliage and winged samara seeds.', color: '#EF4444', accentColor: '#FECACA' },
      { id: 'bio-acacia', name: 'Acacia Tree', category: 'BIOLOGY', description: 'Drought-tolerant umbrella-canopied savanna tree with feathery bipinnate leaves.', color: '#EAB308', accentColor: '#FEF08A' },
      { id: 'bio-fern', name: 'Fern', category: 'BIOLOGY', description: 'Ancient vascular non-flowering plant reproducing via microscopic spores under fronds.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'bio-moss', name: 'Moss', category: 'BIOLOGY', description: 'Small non-vascular flowerless plant absorbing moisture directly through dense green mats.', color: '#84CC16', accentColor: '#D9F99D' },
      { id: 'bio-sunflower', name: 'Sunflower', category: 'BIOLOGY', description: 'Tall heliotropic flowering plant whose inflorescence tracks the daily movement of the Sun.', color: '#FACC15', accentColor: '#FEF08A' },
      { id: 'bio-aloe', name: 'Aloe Vera', category: 'BIOLOGY', description: 'Succulent plant species known for thick fleshy leaves containing soothing therapeutic gel.', color: '#14B8A6', accentColor: '#99F6E4' },
      { id: 'bio-lion', name: 'Lion', category: 'BIOLOGY', description: 'Apex predatory felid roaming African savannas living in organized matriarchal prides.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'bio-elephant', name: 'Elephant', category: 'BIOLOGY', description: 'Largest living terrestrial mammal characterized by high intelligence, trunk, and ivory tusks.', color: '#94A3B8', accentColor: '#E2E8F0' },
      { id: 'bio-giraffe', name: 'Giraffe', category: 'BIOLOGY', description: 'Tallest living land mammal equipped with an elongated neck to browse high savanna canopies.', color: '#D97706', accentColor: '#FDE68A' },
      { id: 'bio-zebra', name: 'Zebra', category: 'BIOLOGY', description: 'African equids famous for distinctive black-and-white disruptive camouflage stripes.', color: '#E2E8F0', accentColor: '#334155' },
      { id: 'bio-penguin', name: 'Penguin', category: 'BIOLOGY', description: 'Flightless aquatic marine bird adapted for deep underwater diving in cold currents.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'bio-eagle', name: 'Eagle', category: 'BIOLOGY', description: 'Apex raptor equipped with keen binocular vision, hooked beaks, and muscular talons.', color: '#B45309', accentColor: '#FDE68A' },
      { id: 'bio-frog', name: 'Frog', category: 'BIOLOGY', description: 'Amphibian species undergoing complete metamorphosis from aquatic tadpole to adult.', color: '#22C55E', accentColor: '#86EFAC' },
      { id: 'bio-butterfly', name: 'Butterfly', category: 'BIOLOGY', description: 'Holometabolous flying insect with scale-covered wings and transformative pupal stage.', color: '#EC4899', accentColor: '#FBCFE8' },
      { id: 'bio-octopus', name: 'Octopus', category: 'BIOLOGY', description: 'Eight-armed cephalopod possessing decentralized nervous system and dynamic camouflage.', color: '#8B5CF6', accentColor: '#DDD6FE' },
      { id: 'bio-dolphin', name: 'Dolphin', category: 'BIOLOGY', description: 'Highly intelligent aquatic marine mammal relying on sophisticated biological echolocation.', color: '#0EA5E9', accentColor: '#7DD3FC' },
      { id: 'bio-animal-cell', name: 'Animal Cell', category: 'BIOLOGY', description: 'Eukaryotic cellular unit enclosed by a fluid lipid membrane without rigid walls.', color: '#FB7185', accentColor: '#FECDD3' },
      { id: 'bio-plant-cell', name: 'Plant Cell', category: 'BIOLOGY', description: 'Eukaryotic cell containing a cellulose cell wall, large vacuole, and photosynthetic chloroplasts.', color: '#4ADE80', accentColor: '#BBF7D0' },
      { id: 'bio-nucleus', name: 'Nucleus', category: 'BIOLOGY', description: 'Double-membrane cellular organelle storing the eukaryotic organism genomic DNA.', color: '#A855F7', accentColor: '#E9D5FF' },
      { id: 'bio-mitochondria', name: 'Mitochondrion', category: 'BIOLOGY', description: 'Cellular power plant synthesizing adenosine triphosphate (ATP) via aerobic respiration.', color: '#F43F5E', accentColor: '#FECDD3' },
      { id: 'bio-rbc', name: 'Red Blood Cell', category: 'BIOLOGY', description: 'Biconcave erythrocyte packed with iron-rich hemoglobin to transport respiratory oxygen.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'bio-neuron', name: 'Neuron', category: 'BIOLOGY', description: 'Electrically excitable nerve cell transmitting electrochemical signals along axons.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'bio-chromosome', name: 'Chromosome', category: 'BIOLOGY', description: 'Threadlike structure of coiled DNA and histone proteins carrying hereditary genes.', color: '#C084FC', accentColor: '#E9D5FF' },
      { id: 'bio-bacterium', name: 'Bacterium', category: 'BIOLOGY', description: 'Single-celled microscopic prokaryotic organism lacking a membrane-bound nucleus.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'bio-virus', name: 'Virus', category: 'BIOLOGY', description: 'Submicroscopic infectious biological agent capable of replicating only inside host cells.', color: '#F97316', accentColor: '#FED7AA' },
      { id: 'bio-dna-helix', name: 'DNA Strand', category: 'BIOLOGY', description: 'Double helix molecule composed of nucleotide base pairs encoding the blueprint of life.', color: '#06B6D4', accentColor: '#A5F3FC' },
    ],
  },
  {
    id: 'MEDICINE',
    name: 'MEDICINE',
    tagline: 'HUMAN ANATOMY, PATHOLOGY & CLINICAL CARE',
    description: 'Navigate corridors featuring vital organs, skeletal anatomy, diagnostics, and clinical equipment.',
    themeColor: '#E63956',
    wallColor: '#9F1239',
    wallGlow: 'rgba(230, 57, 86, 0.4)',
    bgGradient: 'from-rose-950 via-slate-900 to-red-950',
    accentColor: '#FDA4AF',
    items: [
      { id: 'med-heart', name: 'Human Heart', category: 'MEDICINE', description: 'Muscular four-chambered organ that pumps blood continuously through systemic circulation.', color: '#F43F5E', accentColor: '#FECDD3' },
      { id: 'med-brain', name: 'Human Brain', category: 'MEDICINE', description: 'Central nervous system organ comprising billions of neurons regulating thought and homeostasis.', color: '#FB7185', accentColor: '#FFE4E6' },
      { id: 'med-lungs', name: 'Human Lungs', category: 'MEDICINE', description: 'Pair of spongy respiratory organs facilitating gaseous exchange of oxygen and carbon dioxide.', color: '#FDA4AF', accentColor: '#FFF1F2' },
      { id: 'med-liver', name: 'Human Liver', category: 'MEDICINE', description: 'Vital metabolic organ responsible for detoxification, glycogen storage, and bile production.', color: '#B91C1C', accentColor: '#FCA5A5' },
      { id: 'med-kidney', name: 'Human Kidney', category: 'MEDICINE', description: 'Pair of bean-shaped filtration organs regulating fluid balance, electrolytes, and waste excretion.', color: '#BE123C', accentColor: '#FDA4AF' },
      { id: 'med-stomach', name: 'Human Stomach', category: 'MEDICINE', description: 'J-shaped digestive organ utilizing hydrochloric acid and pepsin to break down ingested nutrients.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'med-femur', name: 'Femur', category: 'MEDICINE', description: 'Thigh bone, the longest, strongest, and most dense structural bone in the human skeleton.', color: '#E2E8F0', accentColor: '#F1F5F9' },
      { id: 'med-spine', name: 'Spine (Vertebral Column)', category: 'MEDICINE', description: 'Segmented skeletal column providing torso axial support while protecting the spinal cord.', color: '#CBD5E1', accentColor: '#F8FAFC' },
      { id: 'med-skull', name: 'Skull (Cranium)', category: 'MEDICINE', description: 'Bony skeletal framework enclosing and shielding the brain and housing sensory organs.', color: '#E2E8F0', accentColor: '#FFFFFF' },
      { id: 'med-rbc', name: 'Red Blood Cell', category: 'MEDICINE', description: 'Erythrocyte transporting respiratory oxygen from alveolar capillaries to systemic tissues.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'med-wbc', name: 'White Blood Cell', category: 'MEDICINE', description: 'Leukocyte immune defender neutralizing invasive bacterial, fungal, and viral pathogens.', color: '#67E8F9', accentColor: '#CFFAFE' },
      { id: 'med-neuron', name: 'Neuron', category: 'MEDICINE', description: 'Signaling unit of the nervous system transmitting electrical action potentials through synaptic junctions.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'med-stethoscope', name: 'Stethoscope', category: 'MEDICINE', description: 'Diagnostic acoustic device used to auscultate cardiac valve murmurs and bronchial breath sounds.', color: '#0284C7', accentColor: '#BAE6FD' },
      { id: 'med-syringe', name: 'Syringe', category: 'MEDICINE', description: 'Piston-driven clinical instrument used to administer intramuscular injections and intravenous drugs.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'med-thermometer', name: 'Thermometer', category: 'MEDICINE', description: 'Clinical diagnostic instrument used to quantify human body core temperature and diagnose pyrexia.', color: '#F43F5E', accentColor: '#FECDD3' },
      { id: 'med-xray', name: 'X-Ray Imaging', category: 'MEDICINE', description: 'High-energy electromagnetic radiation revealing skeletal fractures, joint dislocations, and densitometry.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'med-mri', name: 'MRI Scanner', category: 'MEDICINE', description: 'Medical imaging technology utilizing superconducting magnets to generate high-contrast soft tissue tomography.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'med-microscope', name: 'Medical Microscope', category: 'MEDICINE', description: 'Laboratory optical system magnifying histopathological biopsies and bacterial smear samples.', color: '#A78BFA', accentColor: '#DDD6FE' },
      { id: 'med-ecg', name: 'ECG Monitor', category: 'MEDICINE', description: 'Cardiological apparatus recording myocardium electrical depolarisation waveforms (P-Q-R-S-T).', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'med-mask', name: 'Surgical Mask', category: 'MEDICINE', description: 'Fluid-resistant barrier protecting patients and clinicians against droplet-transmitted pathogens.', color: '#38BDF8', accentColor: '#BAE6FD' },
    ],
  },
  {
    id: 'FINANCE',
    name: 'FINANCE',
    tagline: 'CURRENCIES, MARKETS & CAPITAL ASSETS',
    description: 'Explore modern financial hubs filled with banking architecture, stock charts, currencies, and portfolios.',
    themeColor: '#F59E0B',
    wallColor: '#B45309',
    wallGlow: 'rgba(245, 158, 11, 0.4)',
    bgGradient: 'from-amber-950 via-slate-900 to-yellow-950',
    accentColor: '#FCD34D',
    items: [
      { id: 'fin-coin', name: 'Coin (Specie)', category: 'FINANCE', description: 'Standardized piece of metallic legal tender issued by central monetary authorities.', color: '#FBBF24', accentColor: '#FEF08A' },
      { id: 'fin-banknote', name: 'Banknote', category: 'FINANCE', description: 'Negotiable fiat paper currency issued by a sovereign central bank payable on demand.', color: '#34D399', accentColor: '#A7F3D0' },
      { id: 'fin-creditcard', name: 'Credit Card', category: 'FINANCE', description: 'Plastic or metal transaction card permitting consumers to borrow credit funds at point of sale.', color: '#60A5FA', accentColor: '#BFDBFE' },
      { id: 'fin-wallet', name: 'Wallet', category: 'FINANCE', description: 'Physical or cryptographic digital repository storing monetary notes, payment tokens, and cards.', color: '#B45309', accentColor: '#FDE68A' },
      { id: 'fin-piggybank', name: 'Piggy Bank', category: 'FINANCE', description: 'Classic physical coin receptacle fostering early habits of savings and capital accumulation.', color: '#FB7185', accentColor: '#FECDD3' },
      { id: 'fin-bank', name: 'Bank Building', category: 'FINANCE', description: 'Chartered depository institution providing credit creation, asset custody, and transaction clearing.', color: '#E2E8F0', accentColor: '#94A3B8' },
      { id: 'fin-stockchart', name: 'Stock Chart', category: 'FINANCE', description: 'Chronological time-series graph tracking valuation fluctuations of traded equities.', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'fin-candlestick', name: 'Candlestick Chart', category: 'FINANCE', description: 'Technical analysis chart displaying opening, peak, trough, and closing asset price intervals.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'fin-bull', name: 'Bull Market', category: 'FINANCE', description: 'Optimistic macroeconomic condition characterized by rising securities valuations and investor confidence.', color: '#22C55E', accentColor: '#86EFAC' },
      { id: 'fin-bear', name: 'Bear Market', category: 'FINANCE', description: 'Prolonged period of dropping market prices typically defined by a 20 percent drop from recent peaks.', color: '#EF4444', accentColor: '#FECACA' },
      { id: 'fin-currencysym', name: 'Currency Symbol', category: 'FINANCE', description: 'Standardized typographic glyph designating sovereign legal tender ($ € £ ¥ R).', color: '#FBBF24', accentColor: '#FEF08A' },
      { id: 'fin-calc', name: 'Financial Calculator', category: 'FINANCE', description: 'Computational tool computing compound interest, net present value, and amortization tables.', color: '#64748B', accentColor: '#CBD5E1' },
      { id: 'fin-receipt', name: 'Receipt', category: 'FINANCE', description: 'Legally binding documentation acknowledging full settlement of a purchase transaction.', color: '#E2E8F0', accentColor: '#F8FAFC' },
      { id: 'fin-invoice', name: 'Invoice', category: 'FINANCE', description: 'Commercial bill of sale itemizing deliverables, billing dates, and remittance terms.', color: '#93C5FD', accentColor: '#DBEAFE' },
      { id: 'fin-portfolio', name: 'Investment Portfolio', category: 'FINANCE', description: 'Diversified bundle of capital assets spanning equities, government bonds, real estate, and cash.', color: '#8B5CF6', accentColor: '#DDD6FE' },
      { id: 'fin-bond', name: 'Bond Certificate', category: 'FINANCE', description: 'Fixed-income debt instrument wherein an investor loans capital to an issuing corporate or state body.', color: '#0284C7', accentColor: '#BAE6FD' },
      { id: 'fin-share', name: 'Company Share', category: 'FINANCE', description: 'Fractional equity stake conferring shareholder voting rights and proportional dividend claims.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'fin-interest', name: 'Interest Rate Concept', category: 'FINANCE', description: 'Annualized cost of borrowing capital or lender yield expressed as a percentage of principal balance.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'fin-inflation', name: 'Inflation Concept', category: 'FINANCE', description: 'Persistent rise in general consumer price indices eroding real purchasing power of money.', color: '#F97316', accentColor: '#FED7AA' },
      { id: 'fin-forex', name: 'Exchange Rate Concept', category: 'FINANCE', description: 'Relative bilateral price of one national currency expressed in units of foreign foreign tender.', color: '#06B6D4', accentColor: '#A5F3FC' },
    ],
  },
  {
    id: 'TECHNOLOGY',
    name: 'TECHNOLOGY',
    tagline: 'COMPUTING, ALGORITHMS & DIGITAL HARDWARE',
    description: 'Explore futuristic cyber corridors with servers, microchips, AI nodes, robotics, and code syntax.',
    themeColor: '#8B5CF6',
    wallColor: '#6D28D9',
    wallGlow: 'rgba(139, 92, 246, 0.4)',
    bgGradient: 'from-purple-950 via-slate-900 to-violet-950',
    accentColor: '#C4B5FD',
    items: [
      { id: 'tech-desktop', name: 'Desktop Computer', category: 'TECHNOLOGY', description: 'Personal computing workstation designed for high-performance processing at a fixed desk.', color: '#A78BFA', accentColor: '#DDD6FE' },
      { id: 'tech-laptop', name: 'Laptop', category: 'TECHNOLOGY', description: 'Clamshell portable computer integrating display, keyboard, touchpad, and battery in one chassis.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'tech-smartphone', name: 'Smartphone', category: 'TECHNOLOGY', description: 'Mobile handheld computing platform combining high-bandwidth networking, GPS, and multi-touch OS.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'tech-tablet', name: 'Tablet', category: 'TECHNOLOGY', description: 'Slate-form mobile device navigated via direct capacitive touchscreen gesture interaction.', color: '#60A5FA', accentColor: '#BFDBFE' },
      { id: 'tech-robot', name: 'Robot', category: 'TECHNOLOGY', description: 'Programmable electromechanical machine capable of carrying out complex automated physical tasks.', color: '#34D399', accentColor: '#A7F3D0' },
      { id: 'tech-pcb', name: 'Circuit Board (PCB)', category: 'TECHNOLOGY', description: 'Laminated board connecting discrete electronic parts via etched conductive copper tracks.', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'tech-microchip', name: 'Microchip (IC)', category: 'TECHNOLOGY', description: 'Monolithic silicon semiconductor wafer containing billions of microscopic transistors.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'tech-server', name: 'Server Rack', category: 'TECHNOLOGY', description: 'Dedicated enterprise computing system managing centralized data, web hosting, and cloud workloads.', color: '#64748B', accentColor: '#CBD5E1' },
      { id: 'tech-cloud', name: 'Cloud Computing', category: 'TECHNOLOGY', description: 'On-demand delivery of hosted computing services, virtualization, and storage across the internet.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'tech-wifi', name: 'Wi-Fi Symbol', category: 'TECHNOLOGY', description: 'Standardized IEEE 802.11 wireless radio frequency local area networking technology.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'tech-keyboard', name: 'Keyboard', category: 'TECHNOLOGY', description: 'Primary alphanumeric input peripheral converting mechanical key depressions into binary keycodes.', color: '#94A3B8', accentColor: '#E2E8F0' },
      { id: 'tech-mouse', name: 'Computer Mouse', category: 'TECHNOLOGY', description: 'Ergonomic pointing peripheral tracking two-dimensional vector movement on a surface.', color: '#64748B', accentColor: '#CBD5E1' },
      { id: 'tech-camera', name: 'Digital Camera', category: 'TECHNOLOGY', description: 'Optical CMOS sensor capturing light and converting photons into matrix pixel data.', color: '#F43F5E', accentColor: '#FECDD3' },
      { id: 'tech-headphones', name: 'Headphones', category: 'TECHNOLOGY', description: 'Miniature electroacoustic transducers worn over the ear to reproduce stereo audio waveforms.', color: '#C084FC', accentColor: '#E9D5FF' },
      { id: 'tech-drone', name: 'Drone (UAV)', category: 'TECHNOLOGY', description: 'Unmanned multi-rotor aerial vehicle guided autonomously or via radio remote control telemetry.', color: '#F97316', accentColor: '#FED7AA' },
      { id: 'tech-3dprinter', name: '3D Printer', category: 'TECHNOLOGY', description: 'Additive manufacturing machine fabricating physical 3D objects layer-by-layer from CAD models.', color: '#06B6D4', accentColor: '#A5F3FC' },
      { id: 'tech-code', name: 'Coding Symbol (</>)', category: 'TECHNOLOGY', description: 'Universal programming syntax notation representing code tags, markup, and algorithmic logic.', color: '#34D399', accentColor: '#A7F3D0' },
      { id: 'tech-database', name: 'Database (SQL)', category: 'TECHNOLOGY', description: 'Organized relational or NoSQL electronic repository storing structured queried data records.', color: '#3B82F6', accentColor: '#93C5FD' },
      { id: 'tech-nodes', name: 'Network Nodes', category: 'TECHNOLOGY', description: 'Interconnected network topology points routing digital data packets across distributed mesh links.', color: '#A855F7', accentColor: '#E9D5FF' },
      { id: 'tech-ai', name: 'Artificial Intelligence (AI)', category: 'TECHNOLOGY', description: 'Deep neural networks and statistical models performing cognitive tasks, synthesis, and deduction.', color: '#F43F5E', accentColor: '#FECDD3' },
    ],
  },
  {
    id: 'POLITICS',
    name: 'POLITICS',
    tagline: 'CIVIC GOVERNANCE, LAW & DIPLOMATIC INSTITUTIONS',
    description: 'Explore neutral civic corridors containing parliaments, constitutional charters, gavels, and voting ballots.',
    themeColor: '#06B6D4',
    wallColor: '#0E7490',
    wallGlow: 'rgba(6, 182, 212, 0.4)',
    bgGradient: 'from-cyan-950 via-slate-900 to-blue-950',
    accentColor: '#67E8F9',
    items: [
      { id: 'pol-parliament', name: 'Parliament Building', category: 'POLITICS', description: 'National architectural edifice where elected legislators assemble to debate, scrutinize, and enact bills.', color: '#E2E8F0', accentColor: '#94A3B8' },
      { id: 'pol-ballotbox', name: 'Ballot Box', category: 'POLITICS', description: 'Tamper-evident sealed receptacle into which registered voters deposit confidential electoral votes.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'pol-constitution', name: 'Constitution Document', category: 'POLITICS', description: 'Supreme foundational charter codifying citizen civil rights, separation of powers, and state laws.', color: '#FBBF24', accentColor: '#FEF08A' },
      { id: 'pol-flag', name: 'National Flag', category: 'POLITICS', description: 'Official heraldic banner representing the shared identity, sovereignty, and constitutional populace.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'pol-worldmap', name: 'World Map', category: 'POLITICS', description: 'Cartographic projection detailing global geopolitical boundaries and multilateral territories.', color: '#34D399', accentColor: '#A7F3D0' },
      { id: 'pol-govbldg', name: 'Government Building', category: 'POLITICS', description: 'Administrative headquarters of executive ministries administering public services and civil welfare.', color: '#CBD5E1', accentColor: '#E2E8F0' },
      { id: 'pol-ballot', name: 'Voting Ballot', category: 'POLITICS', description: 'Formal paper or electronic instrument allowing voters to designate choices during democratic polls.', color: '#F8FAFC', accentColor: '#94A3B8' },
      { id: 'pol-polmap', name: 'Political Boundary Map', category: 'POLITICS', description: 'Geographic chart distinguishing demarcated jurisdictional borders of states and provinces.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'pol-gavel', name: 'Gavel', category: 'POLITICS', description: 'Ceremonial wooden mallet struck by presiding judges or parliamentary speakers to preserve order.', color: '#B45309', accentColor: '#FDE68A' },
      { id: 'pol-podium', name: 'Podium / Rostrum', category: 'POLITICS', description: 'Elevated oratorical lectern from which civic officials address assemblies and public addresses.', color: '#78716C', accentColor: '#D6D3D1' },
      { id: 'pol-mic', name: 'Microphone', category: 'POLITICS', description: 'Audio transducer capturing speech for broadcast during parliamentary proceedings and debates.', color: '#A8A29E', accentColor: '#E7E5E4' },
      { id: 'pol-debate', name: 'Debate Speech', category: 'POLITICS', description: 'Formally regulated verbal argumentation deliberating proposed statutes, ethics, and reforms.', color: '#60A5FA', accentColor: '#BFDBFE' },
      { id: 'pol-legis', name: 'Legislature Building', category: 'POLITICS', description: 'Civic chamber where statutory committees draft, amend, and ratify public legislation.', color: '#E2E8F0', accentColor: '#94A3B8' },
      { id: 'pol-court', name: 'Court Building (Judiciary)', category: 'POLITICS', description: 'Temple of justice where independent judges adjudicate disputes and uphold statutory rule of law.', color: '#E2E8F0', accentColor: '#CBD5E1' },
      { id: 'pol-policy', name: 'Public Policy Document', category: 'POLITICS', description: 'Official written whitepaper formulating governmental strategy to resolve socioeconomic problems.', color: '#93C5FD', accentColor: '#DBEAFE' },
      { id: 'pol-chamber', name: 'Assembly Chamber', category: 'POLITICS', description: 'Plenary hall configured with amphitheatre seating for democratic representative assemblies.', color: '#0284C7', accentColor: '#BAE6FD' },
      { id: 'pol-handshake', name: 'Diplomatic Handshake', category: 'POLITICS', description: 'International diplomatic protocol affirming mutual treaty ratification and peaceful cooperation.', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'pol-calendar', name: 'Election Calendar', category: 'POLITICS', description: 'Statutory timetable governing candidacy filing, voter roll verification, and voting day operations.', color: '#F43F5E', accentColor: '#FECDD3' },
      { id: 'pol-regdoc', name: 'Civic Registration Document', category: 'POLITICS', description: 'Official certification certifying an individual legal status and democratic voter franchise.', color: '#A78BFA', accentColor: '#DDD6FE' },
      { id: 'pol-speech', name: 'Political Address', category: 'POLITICS', description: 'Public oration communicating strategic state of the nation updates and policy priorities.', color: '#F59E0B', accentColor: '#FDE68A' },
    ],
  },
  {
    id: 'GEOGRAPHY',
    name: 'GEOGRAPHY',
    tagline: 'TOPOGRAPHY, BIOMES & PLANETARY EARTH',
    description: 'Explore planetary mazes filled with tectonic plates, mountain ranges, islands, oceans, and globes.',
    themeColor: '#EC4899',
    wallColor: '#BE185D',
    wallGlow: 'rgba(236, 72, 153, 0.4)',
    bgGradient: 'from-pink-950 via-slate-900 to-rose-950',
    accentColor: '#F472B6',
    items: [
      { id: 'geo-mountain', name: 'Mountain', category: 'GEOGRAPHY', description: 'Prominent elevated landform rising steeply above surrounding terrain through tectonic uplift.', color: '#A8A29E', accentColor: '#E7E5E4' },
      { id: 'geo-volcano', name: 'Volcano', category: 'GEOGRAPHY', description: 'Crustal fissure through which magma, pyroclastic ash, and geothermal gases vent to the surface.', color: '#EF4444', accentColor: '#FECACA' },
      { id: 'geo-glacier', name: 'Glacier', category: 'GEOGRAPHY', description: 'Perennial mass of compressed recrystallized ice slowly deforming and flowing downslope.', color: '#67E8F9', accentColor: '#CFFAFE' },
      { id: 'geo-desert', name: 'Desert Biome', category: 'GEOGRAPHY', description: 'Arid geographic region receiving under 250 millimeters of annual precipitation with sand ergs.', color: '#F59E0B', accentColor: '#FDE68A' },
      { id: 'geo-ocean', name: 'Ocean', category: 'GEOGRAPHY', description: 'Enormous body of saline oceanic water covering approximately 71 percent of planetary surface.', color: '#0284C7', accentColor: '#BAE6FD' },
      { id: 'geo-river', name: 'River', category: 'GEOGRAPHY', description: 'Natural freshwater fluvial channel draining continental catchment basins into lakes or seas.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'geo-waterfall', name: 'Waterfall', category: 'GEOGRAPHY', description: 'Vertical drop of a river channel created by differential erosion across hard and soft rock strata.', color: '#06B6D4', accentColor: '#A5F3FC' },
      { id: 'geo-island', name: 'Island', category: 'GEOGRAPHY', description: 'Isolated terrestrial landmass completely surrounded by marine or freshwater aquatic bodies.', color: '#10B981', accentColor: '#A7F3D0' },
      { id: 'geo-forest', name: 'Temperate Forest', category: 'GEOGRAPHY', description: 'Dense biome dominated by tree canopies regulating carbon storage and regional rainfall.', color: '#16A34A', accentColor: '#86EFAC' },
      { id: 'geo-rainforest', name: 'Tropical Rainforest', category: 'GEOGRAPHY', description: 'Equatorial broadleaf biome characterized by high continuous precipitation and supreme biodiversity.', color: '#22C55E', accentColor: '#A7F3D0' },
      { id: 'geo-lake', name: 'Lake', category: 'GEOGRAPHY', description: 'Localized inland basin of standing fresh or saline water isolated from direct marine flow.', color: '#0EA5E9', accentColor: '#7DD3FC' },
      { id: 'geo-canyon', name: 'Canyon / Gorge', category: 'GEOGRAPHY', description: 'Deep geological cleft bounded by steep escarpments carved over millions of years by river erosion.', color: '#D97706', accentColor: '#FDE68A' },
      { id: 'geo-compass', name: 'Compass', category: 'GEOGRAPHY', description: 'Magnetized directional instrument aligning with geomagnetic poles to indicate cardinal bearings.', color: '#E11D48', accentColor: '#FECDD3' },
      { id: 'geo-globe', name: 'Globe', category: 'GEOGRAPHY', description: 'Accurate three-dimensional spherical scale representation of planetary geography and oceans.', color: '#0284C7', accentColor: '#34D399' },
      { id: 'geo-map', name: 'Topographic Map', category: 'GEOGRAPHY', description: 'Two-dimensional cartographic projection detailing contour elevations, rivers, and settlements.', color: '#FBBF24', accentColor: '#FEF08A' },
      { id: 'geo-continent', name: 'Continent (e.g. Africa)', category: 'GEOGRAPHY', description: 'Major continuous continental landmass bounded by tectonic margins and vast oceans.', color: '#10B981', accentColor: '#6EE7B7' },
      { id: 'geo-equator', name: 'Equator (0° Parallel)', category: 'GEOGRAPHY', description: 'Planetary zero-degree latitude line dividing Earth into Northern and Southern hemispheres.', color: '#EF4444', accentColor: '#FCA5A5' },
      { id: 'geo-latitude', name: 'Latitude Lines', category: 'GEOGRAPHY', description: 'Parallel geographic coordinate lines measuring angular distance north or south from the equator.', color: '#38BDF8', accentColor: '#BAE6FD' },
      { id: 'geo-longitude', name: 'Longitude Meridians', category: 'GEOGRAPHY', description: 'Polar meridian lines measuring angular distance east or west from the Greenwich Prime Meridian.', color: '#818CF8', accentColor: '#C7D2FE' },
      { id: 'geo-plates', name: 'Tectonic Plates', category: 'GEOGRAPHY', description: 'Rigid lithospheric crust plates whose subterranean drift triggers earthquakes and mountain orogeny.', color: '#B45309', accentColor: '#FDE68A' },
    ],
  },
];
